language: android

jdk:
  - openjdk8

script:
  - ./gradlew clean build

before_install:
  # Install SDK license so Android Gradle plugin can install deps.
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > "$ANDROID_HOME/licenses/android-sdk-license"

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: "ZPltrBfCCFDlOiZIaQzScfUTQoYJTyvkSgdMjUYMunYEUKGhkfNHVBRm/+6bd5GUQc5XgwXyDPBRutdZzE8LPs8afeejlxPJFuUskyLh197IjWzN+np65xyT0shkQUB5IGhSRW7e81NrfKUyjSvsbvIxX0PSt5r1TV2914c0vqzouKMLiZvNabn1zi3pKbILE7z4jTrUlzJtt1FJlq4t7oy07DRH+RSiBbtdeLeY16YoL0b2gmUadxDpufZYOKRoJA0b42Cg/ToZ9GJ2rfOo3n5yGfxAzfb1Xcf8B6ozXuLfzzvIsok+boe7JPiL7gAtv6gKxnp4/ClfSRik+Ab/5ktquBNnlFLosgcb4bq5ZWxQSJfWWx5+3hB5aimsc6cDvZm9wOO8oFmP7g0kAsfmL608ZiZG6D+cOr96Zzq6HUmfc/5LhmtRY4FZr5BSYTsPMHDfbcSXXmsF+NBLmRU68sC8yCCBJ4M87qCL8JkyUCk79eiPDTdXLXmNbXtU1t7yXBlZ5IkvTjSdNKPBuSVkt8QMdbjjyR99HN3+5TaNSBvFWRR5HlZ2AViaiwo78z8RzcBBOv/O3fGcCWO4O8wuLqvjSbE5kwoaRkY7On0GoKEDONP+H1bEIEi2B3+mYopxSQAvYsLC2GITZ5WbIw57tXCOFzrb8ZYxYroYE1D2qHo="
    - secure: "q6ofqYnDXccEx6Sjp46ITsVLkpoy/sZbdKw2Ms1BIVwesNk96gt9O3QsC6e57jiIKh8QcvoF7zvhmvUvjneK7gaLtKjB0FLbhOMdrW47TH23TZYs6be2H1KMPVsHwyRCg8q/ApQ7Uxlg0nuj8ZiKrbljO/eOGvTqbn3Wzne1LKu2eHoh2rRIqmAI8PHD13DyMUwenVFuyn6IIjdcXBfTs37l5U5QNUweSpKJyVlOnI2dU9ME2mugMTB5n9JVvFvG429vtlUIFf/96mX/XAAPVMuJjnNxgwx6gAWnqI5J7yqikZAmEm5vxTU/2cOmao8qB3aGqXb9Vec06wq/5qDhNw3tnU0DCzZXBhiRpiWA+UPYNNzwa/XaBuruDDTjNKX5ZkI0o1f+sJkLy6I9aohwUM0Fu63ZTaixNEIdb+qt7QrSAJtRjCyQvo5E07XntrsOzDHE1SsvlRicJGKvE7XHifs5Nugqtgnm+250AJFoKisnsgqhiCjQX5OTWly3KJBZdMGIVxVRaC65OvymTCN2bsDLFRMtabq7oA1UAh4m844zKlcwyX7WJ1ZIZ5QY1mdteZDaekwXUoblV1LkPBU6d4VRNmBoUgPyE9dQzCSwbzHiJTdD3OSYN4neizbwb4XPE8ATM3AEEKYBHY0LQq0QVYaoQvY/nfrzeUEarV5rTfE="

branches:
  except:
    - gh-pages

notifications:
  email: false

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
