name: Publish a release

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  macos-build:
    runs-on: macOS-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Build the repo
        run: ./gradlew clean build

env:
  GRADLE_OPTS: -Dorg.gradle.configureondemand=true -Dorg.gradle.parallel=false -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx3g -XX:MaxPermSize=2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"
